### ISSUE TITLE
请问打码兔的文档在哪里, 我迷路了, 我需要文件直传解析, 现在gem没有支持,我手动调用

### ISSUE THREAD

**Issue by LcpMarvel** [seaify/confirmation_code#2]

**Comment by seaify** [comment]
@LcpMarvel 

不太记得了，但是这个gem的根目录下有个damatuweb.py, 和dama2http.doc, 你可以看下.

晚点会更新下,  上传url和本地文件应该是一个接口，在接口里区分情况，发送不同的请求过去

**Comment by seaify** [comment]
@LcpMarvel 

今天更新了，result = ConfirmationCode.upload('0349.bmp')

upload函数后面，可以传url, 也可以传路径,  可以使用下

**Comment by LcpMarvel** [comment]
ok, thx
